sudo: required
dist: trusty

language: cpp

compiler:
 - gcc

before_script:
 - export curr_path=$PWD
 - cd ..
 - svn co https://oceanai.mit.edu/svn/moos-ivp-aro/releases/moos-ivp-14.7.1 moos-ivp
 - cd moos-ivp
 - sudo apt-get update -q
 - sudo apt-get install -y --force-yes g++ subversion xterm cmake libfltk1.3-dev freeglut3-dev libpng12-dev libjpeg-dev libxft-dev libxinerama-dev libtiff5-dev libtinyxml2-dev libusb-1.0-0-dev mono-runtime libmono-winforms2.0-cil libv4l-dev libopencv-dev libboost1.55-dev libboost-system1.55-dev
 - ./build-moos.sh
 - ./build-ivp.sh
 - export PATH=$PATH:$PWD/bin
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
 - cd "$curr_path"

script:
 - ./build.sh