#!/bin/bash


declare -i VERBOSE=0

for m in M64 M32; do
  for i in 0 1; do
    echo "=== clean"
    git clean -fdx
    make ${m}=1 DEBUG=${i} VERBOSE=${VERBOSE} all samples
    #make ${m}=1 DEBUG=${i} VERBOSE=${VERBOSE} samples
  done
done

make doc VERBOSE=${VERBOSE}
